version: '3.8'

services:
  api:
    build: .
    container_name: monetech-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db-data:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db-data: